name: figma_squircle
description: A new Flutter package project.
version: 0.5.6
homepage: https://github.com/aloisdeniel/figma_squircle

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  vector_math: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: